# Generated by Django 4.2.7 on 2023-11-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_python', '0002_produtos_quantidade_produtos_valor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='produtos',
        ),
    ]
