# Generated by Django 4.2.7 on 2023-11-07 03:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_python', '0006_remove_produtos_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produtos',
            name='valor',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=20),
        ),
    ]
